### ISSUE TITLE
Use holmes after DOMContentLoaded

### ISSUE THREAD

**Issue by bistory** [Haroenv/holmes#32]
Hi !
I am testing holmes for a webapp but it is impossible to make it work if the holmes function is called after DOMContentLoaded.
I'm loading dynamic parts of the app using Ajax and I'm unable to use holmes :-(

Do you have an idea to improve holmes elegantly ?

Thanks !

**Comment by Haroenv** [comment]
What happens if you do `holmes` only after loading the dom content? 

If your data is dynamic and could change at every `input`, then you can also enable the `dynamic` option by setting it to `true`.

Doing it once after `DOMContentLoaded` would look like this:

``` html
<script src="path/to/holmes.js"></script>
<script>
  window.addEventListener('DOMContentLoaded', function() {
    holmes({
      // options here
    });
  }
</script>
```

Does that help you?

Creating a minimal example where you have problems could help me understand your problem and look for a fix.

**Comment by bistory** [comment]
DOMContentLoaded is never called. It is run by the jQuery evalScript option for Ajax requests. I guess the event is called before doing the eval ?

**Comment by Haroenv** [comment]
I don't really understand what you mean, can you show me how the content is generated?

**Comment by bistory** [comment]
Yes no problem, I'll try to explain it better :-)

I have a dashboard that calls pages using jQuery's ajax functions. These functions are able to load HTML plus JS and eval JS in it.
So in my dynamic page, I have snippets that already work :

`<script>
$(function () {
    $('.panel-list .page').click(function () {
        load_page($(this).data('id'));
        panel.close();
        return false;
    });

```
$('#add-page-button').click(function () {
    if(wysiwyg.instance !== null) {
        wysiwyg.forceSave();
    }
});
holmes({
    input: '#panel-search',
    find: '.panel-list li',
    placeholder: 'no results', //optional
    class: {
        hidden: 'hidden' //optional
    }
});
```

});
</script>`

I added holmes but it relies on DOMContentLoaded event to work. The problem is that this event is not triggered at all once the main page has been loaded by the browser. In other words AJAX requests don't trigger the event.

So I'm searching a way to use holmes without depending on DOMContentLoaded...

**Comment by Haroenv** [comment]
You could trigger it in the callback of the `AJAX` call maybe?

**Comment by bistory** [comment]
It won't work as DOMContentLoaded is not triggered and all you code is wrapped into an event listener.

**Comment by Haroenv** [comment]
Aha, I understand what's going on now! Maybe we could put the `DOMContentLoaded` event listener under an option (which defaults to `true`) and otherwise immediately do the actual content of Holmes. Can you give me an example page on [codepen](http://codepen.io) or in a [gist](https://gist.github.com) to experiment with?

**Comment by Haroenv** [comment]
Can you check out the [feature/instant-or-ajax](https://github.com/Haroenv/holmes/tree/feature/instant-or-ajax) branch?

**Comment by bistory** [comment]
Yeah :)
I'll test that tomorrow ;-)

**Comment by Haroenv** [comment]
Cool, faites le moi savoir 👍

**Comment by bistory** [comment]
Ca fonctionne parfaitement ;-)
