### ISSUE TITLE
Not really an issue, but a couple of questions

### ISSUE THREAD

**Issue by kricir** [Haroenv/holmes#39]
I am curious if there is a way to fix, I am loading all of my elements as hidden by default, however when I start typing into the search field, my elements start showing... What I would like is as I delete all text from the search field, it shows all elements because "" is found in all search terms, instead I want everything to be hidden?

Second question I would prefer to add the ability to set a minimum number of characters in the search field before it starts revealing my hidden elements, like the ability to have to type 3 characters then it starts filtering?

**Comment by Haroenv** [comment]
Hello Richard

I've quickly read through your ideas (it's early morning here) and these two suggestions aren't possible yet. 

I understand that you can see the use in those, and searching is inherently a very diverse field. 

Because these aren't run-time, but rather configuration options, I see them feasible to implement, and will probably do when I find some time for it. 

I'd solve the first problem by adding an item to `class:` called `empty`, which should describe the initial class and the class when you empty the input. 

I was thinking about what name to give your second idea, something like `initialCharacters`, but I find that kinda dubious. Do you have a suggestion?

**Comment by kricir** [comment]
Haroenv,

Thanks for your response, I will attempt what you say about adding a class for empty, and see if I can engineer that in somehow.

I would think a setting along the lines of `minCharacters: 0`, then around the `for` loop could wrap it with a `while (searchString.length >= minCharacters)` could prevent/allow the search function to run

**Comment by Haroenv** [comment]
Aha, `minCharacters` is a good idea! I'd implement it in the same way the difference between instant being true or false. Feel free to leave a pull request if you want this

**Comment by Haroenv** [comment]
I split this up in #44 and #45.

**Comment by Haroenv** [comment]
You can now solve the first problem by using the `onEmpty` callback I think.
