### ISSUE TITLE
Highlight search term

### ISSUE THREAD

**Issue by mischah** [Haroenv/holmes#4]
Wouldn’t it be cool to highlight the searchterm within in the result?

Like this:
![image](https://cloud.githubusercontent.com/assets/441011/15801768/e0fdc1da-2a9f-11e6-950d-9383b6a4d137.png)

**Comment by Haroenv** [comment]
The searching is done with `textContent`. That means that it disregards every piece of dom except the actual text. As advantage this will give all of the text, and is very fast in that. Because of that the matched index isn't possible without computational overhead (getting the index a second time to show the highlight). 

However if someone finds a nice way to do this, I'm happy to incorporate this.

relevant LOC: https://github.com/Haroenv/holmes/blob/gh-pages/js/holmes.js#L54

**Comment by LukyVj** [comment]
I thought about it too, maybe using a regex and replace or so ?

**Comment by aarohmankad** [comment]
I've started working on this issue. The search terms can now be highlighted. However, there are issues with styling of the text once it is replaced with the highlighted text.

**Comment by aarohmankad** [comment]
I may use @LukyVj's suggestion on using regex.

**Comment by Haroenv** [comment]
Looks like a good start, but what could be pitfalls are nested html, I'm thinking that could override the structure. Make sure it's tested properly @aarohmankad. Keep me in the loop!

**Comment by LukyVj** [comment]
Whoop whoop 🎉 

---

Wow, @aarohmankad, just tried your thing, it's just amazing. 
Well done, looking forward to the next iteration 👍

**Comment by Haroenv** [comment]
I've tried your version too @aarohmankad. The problem I see is that since `textContent` (by design) doesn't take the html in account, the content is discarded (originally it was `<blockquote>...<cite>...</cite></blockquote>`. Your version discarded that by setting the `innerHTML` without being sure what that was on beforehand. You'll probably have to get the matched word out with regex (after a setting has been set, wouldn't want to do this every time) and then find its index back in `innerHTML` instead of `textContent`. 

Maybe another option would be to simply `.replace()` the search string in the `innerHTML` with `<mark>...</mark>` (giving some style to `mark` in the demo).

**Comment by jarrydfillmore** [comment]
Sweet!

**Comment by LukyVj** [comment]
I thought this might be helpful http://codepen.io/tomhodgins/pen/Pzmqbr

**Comment by LukyVj** [comment]
Is it still a thing ?

**Comment by Haroenv** [comment]
The same issues are still not resolved (messing with `innerHTML` of the matched documents discards all nested `html` in the element, and solving it with a `regex` feels kinda wrong to me). If anyone finds a solution that works with their use case, and feels like it'd be possible to implement, I'd love to see your work.

**Comment by LukyVj** [comment]
>  and solving it with a regex feels kinda wrong to me

This feels wrong to me :(
