### ISSUE TITLE
Add docs, etc to bower ignore

### ISSUE THREAD

**Issue by lukasoppermann** [Haroenv/holmes#53]
Hey,

when installing via bower you are pulling quite a load from the server. I think the following should be added to the `bower.json` ignore.
- docs/
- css/
- images/
- js/microlight.js
- index.html
- deploy.sh
- install.json (?)
- package.json
- .bower.json (? what does this do?)

Maybe it would make sense to move to a more comment js structure like so:
- src
- dist
- test
- docs/ 
- examples/
  - css/
  - ...

Using some kind of simple gulp script you could minify the js file and move it to dist and than ignore everything but fist for `bower`.

**Comment by Haroenv** [comment]
Good point, I didn't ignore those because in `npm` usually the whole repository (with demo, docs etc.) is copied to the local filesystem. 

I'll add those ignores to the `bower.json` now.

I won't change the folder structure for `examples` though, because I'm hosting my documentation on github pages, and keeping `index.html` at the root allows me to link to `haroen.me/holmes/` and not `haroen.me/holmes/example`

**Comment by lukasoppermann** [comment]
Ahh, okay, I understand.

**Comment by Haroenv** [comment]
closed in #54
